version: "3.9"

services:
  cash_tracker_db:
    image: "postgres:latest"
    restart: unless-stopped
    container_name: cash_tracker_db
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_DATABASE_PASSWORD
      - POSTGRES_USER=$POSTGRES_DATABASE_USER
      - POSTGRES_DB=$POSTGRES_DATABASE_NAME
    ports:
      - "$POSTGRES_DATABASE_PORT:5432"